### PR TITLE
Correct the 'indexed getter' cross-reference

### PR DESCRIPTION
**Pull request by Ms2ger**
***
<a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/pull/679.html" title="Last updated on Mar 7, 2019, 2:23 PM UTC (b549ba8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/679/a94e4b4...b549ba8.html" title="Last updated on Mar 7, 2019, 2:23 PM UTC (b549ba8)">Diff</a>

### CODE REVIEW

**Comment by Ms2ger** [comment]
@tabatkins I accidentally pointed at https://drafts.css-houdini.org/css-typed-om-1/#cssnumericarray-indexed-getter here; I'm surprised that spec defines such a generic term globally. Is that intentional?

**Comment by tabatkins** [comment]
> I'm surprised that spec defines such a generic term globally

It doesn't, the definition is scoped to CSSNumericArray: `<dfn data-dfn-for="CSSNumericArray" data-dfn-type="dfn" data-export="" id="cssnumericarray-indexed-getter">indexed getter<a class="self-link" href="#cssnumericarray-indexed-getter"></a></dfn>`

However, this might be the *only* defining instance of that term, so an unqualified autolink will match the dfn without complaining.  Was that term always "indexed property getter" in WebIDL? If so, I should update TypedOM to use the right word. ^_^

**Comment by Ms2ger** [comment]
>  Was that term always "indexed property getter" in WebIDL? If so, I should update TypedOM to use the right word. ^_^

At least as far back as https://www.w3.org/TR/2011/WD-WebIDL-20110927/ :)

**Comment by tabatkins** [comment]
Cool, I've just renamed the Typed OM term properly, and had it link to the WebIDL term. ^_^

**Pull request merged**
