### PR TITLE
Meta: move to GitHub Actions

### PR DESCRIPTION
**Pull request by domenic**

### CODE REVIEW

**Comment by TimothyGu** [comment]
LGTM if it works. I don't see Actions running on this PR though?

**Comment by domenic** [comment]
Yeah, that is a bit worrying. Maybe it's a function of the rights I have to the repo? :/

**Comment by domenic** [comment]
Yeah, so, we merged #987 but it's not deploying.

I'm somewhat hopeful that even if GitHub won't run first-time actions for PRs, it'll start running them after we merge this? So it might be worth trying to merge this and seeing what happens?

**Comment by annevk** [comment]
@heycam maybe you have to turn this on somewhere as admin?

**Comment by domenic** [comment]
Ahah, I had the wrong branch name. When that is corrected it ran. Can I get a green checkmark?

**Review by TimothyGu — APPROVED** [review]

**Pull request merged**
