### PR TITLE
Remove [NoInterfaceObject].

### LINKED ISSUE #430: No mixin [NoInterfaceObject] usage
Per https://github.com/heycam/webidl/pull/423#issuecomment-326332460 this exists. I'd like to study such usage and see if we can get rid of it.

### PR DESCRIPTION
**Pull request by Ms2ger**
Fixes #430.

***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/609.html" title="Last updated on Jan 14, 2019, 4:01 PM UTC (98de7f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/609/6ec828c...Ms2ger:98de7f7.html" title="Last updated on Jan 14, 2019, 4:01 PM UTC (98de7f7)">Diff</a>

### CODE REVIEW

**Comment by domenic** [comment]
I guess the real work here is PRing every spec that uses it, and then trying to ship and see if the result is web-compatible...

**Comment by Ms2ger** [comment]
Indeed. I'm not sure if all the specs that use it are maintained, though. Perhaps one of the browser vendors should try shipping first and see what happens.

**Comment by foolip** [comment]
Greping https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl reveals surprisingly few remaining uses of this beyond what's already linked in this PR:
https://drafts.csswg.org/css-font-loading/#font-face-source (@tabatkins)
https://drafts.csswg.org/css-regions/#the-region-interface (@atanassov @astearns)
https://w3c.github.io/mediacapture-main/#interface-definition (@aboba @jan-ivar)
https://w3c.github.io/webappsec-feature-policy/#the-policy-object (@clelland)

**Comment by jan-ivar** [comment]
> https://w3c.github.io/mediacapture-main/#interface-definition (@aboba @jan-ivar)

*"Although this specification formally defines `ConstrainablePattern` as a WebIDL interface, it is actually a template or pattern for other interfaces and cannot be inherited directly since the return values of the methods need to be extended,"*, so 👍

**Comment by foolip** [comment]
Ah, sounds like that interface should be marked up as an example in the spec. This would avoid it showing up in reffy-reports, and would avoid the need for `[NoInterfaceObject]`, which presumably isn't something the other interfaces should copy.

**Comment by jan-ivar** [comment]
@foolip How do I do that?

**Comment by foolip** [comment]
@jan-ivar wrapping in `<div class="example">` might to the trick. Or if you want to just avoid it being extracted by reffy, the `exclude` class was added in https://github.com/tidoust/reffy/pull/137 for that purpose.

**Comment by saschanaz** [comment]
Are there still known blockers other than https://github.com/w3c/webappsec-feature-policy/issues/341 or is it the last one?

**Comment by bzbarsky** [comment]
Well, there's the fact that as far as I know browsers haven't shipped the removals done so far, so we don't know whether they're web-compatible, right?

**Comment by saschanaz** [comment]
Yes, although at least some of them are shipped in stable Chrome e.g. `External` from HTML and `DeviceMotionEventRotationRate` etc. from device orientation.

**Comment by domenic** [comment]
We renamed it to [LegacyNoInterfaceObject] and all remaining uses are in Web GL. If Web GL shows signs of wanting to expose their interfaces then we can revisit, but for now let's close...

**Pull request closed without merging**
