### PR TITLE
Move conventions and conformance to appendices

### PR DESCRIPTION
**Pull request by domenic**
It's nice to get to the good stuff sooner.

### CODE REVIEW

**Comment by tobie** [comment]
Agree re conformance. Typographic conventions become less useful at the end imho, so the question becomes whether we need them at all.

**Comment by marcoscaceres** [comment]
>  Typographic conventions become less useful at the end imho, so the question becomes whether we need them at all.

Ditch 'em, IMO.

**Comment by bzbarsky** [comment]
To the extent that we have nontrivial semantics via typography (think the '?' thing) we should have it in the document.  If nothing else so that instances of those semantics can link to the thing that explains what the line noise means.

**Comment by marcoscaceres** [comment]
@bzbarsky, good point; but there is stuff there that is well-known, like what a non-normative example looks like.

**Comment by bzbarsky** [comment]
I dunno how well-known it is.  I recently had someone (a browser engine developer) quoting non-normative example text from the HTML spec at me as justification for something that engine was doing that contradicted the normative text...

**Comment by marcoscaceres** [comment]
Browser engineers are the worst. The. Worst.

**Pull request merged**
