### PR TITLE
Use %PromiseProto_then% to 'perform some steps once a promise is settled'.

### LINKED ISSUE #583: Should "perform some steps once a promise is settled" use %PromiseProto_then%?
https://heycam.github.io/webidl/#dfn-perform-steps-once-promise-is-settled

The current spec has

> 1. Let *then* be ? GetMethod(*promise*, "then").

which seems to imply that weird things may happen if you mess with a promise object or the prototype. That seems non-obvious and not particularly useful.

### PR DESCRIPTION
**Pull request by Ms2ger**
Fixes #583.

***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/webidl/pull/611.html" title="Last updated on Jan 15, 2019, 10:27 AM UTC (e79feeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/heycam/webidl/611/d05c8cc...Ms2ger:e79feeb.html" title="Last updated on Jan 15, 2019, 10:27 AM UTC (e79feeb)">Diff</a>

### CODE REVIEW

**Comment by bzbarsky** [comment]
Seems ok.  Do we know what specs use it and what UAs actually do in those cases?  As in, do we need UA bugs?

**Comment by bzbarsky** [comment]
(Also, it looks like this still requires observable creation of an extra Promise, which is not ideal, but I guess those are the tools that the ES spec gives us...)

**Comment by domenic** [comment]
Yeah, there's a larger project of just overhauling all the promise stuff to be simpler and match UAs and merge promises-guide into here. Not today though...

**Comment by littledan** [comment]
This change is (subtly) observable in all sorts of web platform APIs. Would it be possible to add tests for it, e.g., in idlharness.js?

**Comment by littledan** [comment]
@domenic Is there an issue tracking that larger project?

**Comment by domenic** [comment]
https://github.com/heycam/webidl/issues/490, although I will add a comment there expanding what I think the steps are.

**Pull request merged**
